server:
  port: ${LAVALINK_PORT:${PORT:2333}}
  address: 0.0.0.0

lavalink:
  server:
    password: "${LAVALINK_SERVER_PASSWORD:render_pass_123}"
    sources:
      youtube: true
      soundcloud: true
      bandcamp: true
      twitch: true
      vimeo: true
      http: true
      local: false
