services:
  - type: web
    name: jarvis-discord-bot
    runtime: node
    repo: https://github.com/HustleSynth/jarvis-ai # Replace with your repo
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: MONGO_PW
        sync: false
      - key: GOOGLE_AI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_API_KEY2
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY2
        sync: false
      - key: OPENROUTER_API_KEY3
        sync: false
      - key: HF_TOKEN
        sync: false
      - key: HF_TOKEN2
        sync: false
      - key: MIXTRAL_API_KEY
        sync: false
      - key: MIXTRAL_API_KEY2
        sync: false
      - key: OPENROUTER_API_KEY4
        sync: false
      - key: OPENROUTER_API_KEY5
        sync: false
      - key: OPENROUTER_API_KEY6
        sync: false
      - key: OPENROUTER_API_KEY7
        sync: false
      - key: OPENROUTER_API_KEY8
        sync: false
      - key: GROQ_API_KEY3
        sync: false
      - key: GOOGLE_AI_API_KEY2
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ADMIN_USER_ID
        sync: false
      - key: PORT
        generateValue: true
